In [2]:
import torch
x = torch.tensor([1,2,3])
torch.is_tensor(x)


True

Storage trong PyTorch là vùng bộ nhớ thô dùng để chứa dữ liệu của tensor (một tensor có thể chia sẻ cùng một storage với tensor khác).
data_ptr() trong PyTorch là một method của Tensor hoặc Storage dùng để trả về địa chỉ con trỏ (memory address) đến vùng nhớ chứa dữ liệu thực sự của tensor trong RAM (hoặc GPU memory nếu tensor nằm trên CUDA).

In [ ]:
import torch

x = torch.tensor([1,2,3])

s=x.storage()

print(torch.is_storage(x))
print(torch.is_storage(s))

y=x[:2] #y là view của x
print(y.storage().data_ptr()==x.storage().data_ptr()) #cùng 1 storage

False
True
True


In [11]:
import torch

a = torch.tensor([1,2,3], dtype=torch.float32)
b=torch.tensor([1+2j,3+4j], dtype=torch.complex64)

print(torch.is_complex(a))
print(torch.is_complex(b))

#tao tensor so phuc tu phan thuc va phan ao
real = torch.tensor([1.0,2.0])
imag = torch.tensor([3.0,4.0])

z = torch.complex(real, imag)
print(z)
print(torch.is_complex(z))

False
True
tensor([1.+3.j, 2.+4.j])
True


torch.is_complex kiểm tra dtype của tensor.

Không áp dụng cho int, float, bool vì chúng không có phần ảo.

In [12]:
import torch

z = torch.tensor([1+2j, 3+4j], dtype=torch.complex64)
print(torch.is_conj(z))
z_conj=torch.conj(z)
print(torch.is_conj(z_conj))

z_realized = torch.resolve_conj(z_conj)
print(torch.is_conj(z_realized))
print(z_realized)



False
True
False
tensor([1.-2.j, 3.-4.j])


torch.is_conj(x) kiểm tra xem tensor có conjugate bit không, chứ không phải kiểm tra giá trị có đúng là số phức liên hợp hay không.

Nếu bạn muốn tính giá trị liên hợp thật sự, dùng torch.resolve_conj().

In [13]:
import torch

a = torch.tensor([1,2,3], dtype = torch.int)
b=torch.tensor([1.0,2.0,3.0], dtype = torch.float32)
c=torch.tensor([1+2j,3+4j], dtype = torch.complex64)
d=torch.tensor([True,False])

print(torch.is_floating_point(a))
print(torch.is_floating_point(b))
print(torch.is_floating_point(c))
print(torch.is_floating_point(d))


False
True
False
False


input phải là tensor vô hướng (0-dim, tức là chỉ chứa một giá trị).

Nếu giá trị ≠ 0 → trả về True.

Nếu giá trị = 0 → trả về False.

Nếu truyền tensor có nhiều phần tử → báo lỗi.

In [14]:
import torch

a = torch.tensor(3)
b= torch.tensor(1)
c = torch.tensor([1,2])

print(torch.is_nonzero(a))
print(torch.is_nonzero(b))

try:
    print(torch.is_nonzero(c))
except Exception as e:
    print("Loi:",e)
    

True
True
Loi: Boolean value of Tensor with more than one value is ambiguous


torch.set_default_dtype dùng để đặt kiểu dữ liệu mặc định (default floating-point dtype) cho các tensor float mà bạn tạo mà không chỉ định dtype

In [15]:
import torch

a = torch.tensor([1.0 , 2.0, 3.0])
print(a.dtype)

torch.set_default_dtype(torch.float64)

b=torch.tensor([1.0 , 2.0, 3.0])
print(b.dtype)

c=torch.tensor([1,2,3])
print(c.dtype)

torch.float32
torch.float64
torch.int64


d là một torch.dtype thuộc loại floating-point (torch.float32, torch.float64, torch.float16, torch.bfloat16).

Ảnh hưởng đến tensor float mới được tạo sau khi gọi hàm.

Không ảnh hưởng đến tensor integer hay bool.

In [17]:
print(torch.get_default_dtype())

torch.float64


In [1]:
import torch

x = torch.tensor([1.0,2.0])
print(x.device)

if torch.cuda.is_available():
    torch.set_default_device('cuda')
    print(torch.get_default_device())
    
y= torch.tensor([2,2])
print(y.device)

torch.set_default_device('cpu')
z = torch.tensor([3.0, 3.0])
print(z.device)

cpu
cpu
cpu


Hàm này chỉ ảnh hưởng đến tensor tạo mới sau khi gọi.

Không tự động chuyển tensor cũ sang device mới.

Nếu có nhiều GPU, bạn có thể chọn GPU cụ thể

torch.set_default_tensor_type là hàm trong PyTorch dùng để đặt loại Tensor mặc định cho tất cả Tensor mới được tạo.
Khác với torch.set_default_dtype (chỉ đổi dtype của float), hàm này cho phép bạn đổi hẳn kiểu Tensor (ví dụ: torch.FloatTensor, torch.DoubleTensor, torch.cuda.FloatTensor)

In [2]:
import torch

x= torch.tensor([1.0, 2.0])
print(x)
print(x.type())

torch.set_default_tensor_type(torch.DoubleTensor)
y = torch.tensor([1.0 ,2.0 ,3.0])
print(y)
print(y.type())

if torch.cuda.is_available():
    torch.set_default_tensor_type(torch.cuda.FloatTensor)
    z = torch.tensor([1.0 ,2.0,3.0])
    print(z.device)
    print(z.type())
    
torch.set_default_tensor_type(torch.FloatTensor)

tensor([1., 2.])
torch.FloatTensor
tensor([1., 2., 3.])
torch.DoubleTensor


c:\Users\eciti\miniconda3\Lib\site-packages\torch\__init__.py:1264: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\tensor\python_tensor.cpp:436.)
  _C._set_default_tensor_type(t)


Hàm này ảnh hưởng toàn cục đến việc tạo Tensor mới trong chương trình.

Thay đổi này chỉ có hiệu lực sau khi gọi (Tensor đã tạo trước đó không bị đổi).

Thường dùng khi:

Muốn mặc định tất cả Tensor tạo ra ở dạng float64.

Muốn Tensor mặc định ở GPU mà không cần device='cuda' mỗi lần.