Trong Python API của OpenCV, cv2.Point không tồn tại.
Cú pháp cv::Point chỉ dùng trong C++ OpenCV API, còn Python thì chỉ dùng tuple/list hoặc numpy array để biểu diễn điểm.

In [3]:
import cv2
import numpy as np

#Điểm 2D, 3D, và Rectangle

pt2i = (10, 20)
pt2f = (10.5, 20.7)
pt3f = (1.0, 2.0, 3.0)
rec = (5, 5, 5, 5)
print("pt2i", pt2i, "pt2f", pt2f,"pt3f", pt3f,"rec", rec)

pt2i (10, 20) pt2f (10.5, 20.7) pt3f (1.0, 2.0, 3.0) rec (5, 5, 5, 5)


Trong C++ OpenCV có class cv::Size và cv::Scalar.

Nhưng trong Python OpenCV (cv2) không có cv2.Size hay cv2.Scalar.

Python wrapper đơn giản hơn: dùng tuple/list hoặc NumPy array thay thế.

In [5]:
#Size và scalar

sz = (640, 480)
color = (0, 128, 255) #BGR
print("Size:", sz, "Color:", color)

Size: (640, 480) Color: (0, 128, 255)


Trong Python, cv2 không có class Matx33f – thay vào đó ta dùng NumPy array để làm ma trận.

In [4]:
#Mat va Matx

#Tao Mat tu Numpy

import numpy as np
import cv2
mat = np.arange(12, dtype=np.float32).reshape(3, 4)
print("Mat:\n", mat)

#Ma tran co dinh Matx33f va cac phep toan
m3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]], dtype=np.float32)
det = cv2.determinant(m3)
tr = cv2.trace(m3)
print("Matx33f:\n", m3)
print("Determinant:", det, "Trace:", tr)

Mat:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Matx33f:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Determinant: 0.0 Trace: (15.0, 0.0, 0.0, 0.0)


cv2.Vec3b và cv2.Complexf là kiểu dữ liệu C++ API trong OpenCV, Python không có các class này.
Trong Python, ta sẽ dùng NumPy để biểu diễn vector hoặc số phức.

In [6]:
# Vec và Complex
v3b = np.array([1, 2, 3], dtype=np.uint8)
print("Vec3b:", v3b, "dtype:", v3b.dtype)

cplx = np.complex64(complex(2, 3))
print("Complex:", cplx, "Real:", cplx.real, "Imag:", cplx.imag)

Vec3b: [1 2 3] dtype: uint8
Complex: (2+3j) Real: 2.0 Imag: 3.0


Không có cv2.Range.

Dùng NumPy slicing: mat[1:3, 1:3].

In [4]:
#Range va slicing
mat = np.arange(25, dtype=np.float32).reshape(5, 5)
sub = mat[1:3, 1:3]
print("Sub-matrix [1:3, 1:3]:\n", sub)

Sub-matrix [1:3, 1:3]:
 [[ 6.  7.]
 [11. 12.]]


In [9]:
#Umat (OpenCL)

umat = cv2.UMat(mat)
blur = cv2.GaussianBlur(umat, (5, 5), 1.0).get()
print("UMat Gaussian Blur:\n", blur)

UMat Gaussian Blur:
 [[ 4.238145   4.6407647  5.531788   6.4228106  6.82543  ]
 [ 6.2512445  6.6538644  7.544887   8.43591    8.83853  ]
 [10.706359  11.108978  12.000001  12.891024  13.293643 ]
 [15.161471  15.564092  16.455114  17.346136  17.748756 ]
 [17.17457   17.57719   18.468214  19.359236  19.761854 ]]


In [11]:
#InputArray/OutputArray placeholder

gray = cv2.cvtColor(mat, cv2.COLOR_GRAY2BGR)
print("Gray to BGR:\n", gray.shape)

Gray to BGR:
 (5, 5, 3)


cv2.MatExpr chỉ tồn tại trong OpenCV C++ API, Python không có class này.

Trong Python, để thực hiện các biểu thức ma trận (matrix expressions) kiểu mat * 2 + 5, bạn chỉ cần dùng NumPy trực tiếp

In [6]:
import cv2
import numpy as np
#MatEXpr
expr =  mat* 2 + 5
print("MatExpr result:\n", expr)

MatExpr result:
 [[ 5.  7.  9. 11. 13.]
 [15. 17. 19. 21. 23.]
 [25. 27. 29. 31. 33.]
 [35. 37. 39. 41. 43.]
 [45. 47. 49. 51. 53.]]


mat.flat

Trả về một numpy.flatiter: iterator giúp duyệt từng phần tử trong mảng 2D/đa chiều như 1D.

Không tạo bản copy, tiết kiệm bộ nhớ.

sum(it)

Duyệt lần lượt từng phần tử qua iterator it và cộng dồn.

Kết quả bằng mat.sum(), nhưng dùng cú pháp iterator.

In [7]:
#iterators
it = mat.flat
print("Sum via iterator:", sum(it))

Sum via iterator: 300.0


cv2.TermCriteria không tạo ra một object có thuộc tính .maxCount, .epsilon như trong C++. Thay vào đó, nó trả về một tuple (type, maxCount, epsilon).

In [9]:
#TermCriteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
print("TermCriteria:", criteria)

# Ví dụ kmeans
data = np.float32([[1, 2], [1, 4], [1, 0],
                   [10, 2], [10, 4], [10, 0]])

compactness, labels, centers = cv2.kmeans(
    data, 2, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS
)

print("Centers:\n", centers)

TermCriteria: (3, 10, 1.0)
Centers:
 [[ 1.  2.]
 [10.  2.]]


In [ ]:
import numpy as np
import pandas as pd

print("OpenCV operations on array")
print("="*60)

#Tao du lieu mau
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.uint8)
b = np.array([[10, 20, 30], [40, 50, 60]], dtype=np.uint8)

print(f"a= \n{a}")
print(f"b= \n {b}")
print()

#Tao dictionary chua tat ca cac vi du

OpenCV operations on array
a= 
[[1 2 3]
 [4 5 6]]
b= 
 [[10 20 30]
 [40 50 60]]



Hàm np.clip trong NumPy dùng để giới hạn (clamp) giá trị của một mảng về một khoảng [min, max] mà bạn chỉ định.

In [16]:
#Phep toan so hoc

#cv2.add()

add_result = cv2.add(a, b)
print(add_result)
add_res = np.clip(a.astype(np.int16) + b.astype(np.int16), 0, 255).astype(np.uint8)
print(add_res)

[[11 22 33]
 [44 55 66]]
[[11 22 33]
 [44 55 66]]


In [18]:
#cv2.subtract()
subtract_result = cv2.subtract(b, a)
print(subtract_result)
subtract_res = np.clip(b.astype(np.int16) - a.astype(np.int16), 0, 255).astype(np.uint8)
print(subtract_res)

[[ 9 18 27]
 [36 45 54]]
[[ 9 18 27]
 [36 45 54]]


In [23]:
#cv2.multiply()
multiply_result = np.array(cv2.multiply(a, b)/255.0).astype(np.uint8)
print(multiply_result)
multipply_res = np.clip(a.astype(np.int16) * b.astype(np.int16)/255.0, 0, 255).astype(np.uint8)
print(multipply_res)

[[0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 0 1]]


In [26]:
#cv2.divide()
divide_result = cv2.divide(b.astype(np.float32), a.astype(np.float32)+1e-6)
print(divide_result)
divide_res = np.divide(b.astype(np.float32) , a.astype(np.float32)+1e-6)
print(divide_res)

[[9.99999  9.999995 9.999997]
 [9.999998 9.999998 9.999998]]
[[9.99999  9.999995 9.999997]
 [9.999998 9.999998 9.999998]]
